
version: "3"

services:

    db:
      container_name: crafstman_db
      image: postgres:alpine
      volumes: 
      - ./Crafstman.Setup:/scripts
      - ./Crafstman.Setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      restart: always
      environment:
        POSTGRES_PASSWORD: crafstman_pwd
      ports: 
        - 5432:5432